{% set version = "0.3-45" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-scatterplot3d
  version: {{ version|replace("-", "_") }}

source:
  fn: scatterplot3d_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/scatterplot3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scatterplot3d/scatterplot3d_{{ version }}.tar.gz
  sha256: 2ad524da39f0cb33547693bed52e3d8e917c28580671568036dc3c7a9ca48340

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('scatterplot3d')"           # [not win]
    - "\"%R%\" -e \"library('scatterplot3d')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=scatterplot3d
  license: GPL-2.0-only
  summary: Plots a three dimensional (3D) point cloud.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
