# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R1G6+t5GIcsvDTrqXYG7E9BnPbTiTtirl8St3BCU+6lqiuO30DsASJ39NV7clXrX/7sddMm7PS6BM+eIGqzBHHwBL7ZMSekzSmWlHQ3UiplYAhErdf/ANoCLUxCz5Eki5fDmI9YlHK9e85mJBTHiiI0QN/HaWE844b23Z+2pUBlimKdxfvFOHj0SXt/q70Yfxr3ooiIFMa03LuqGcqcsGmHRju8Epb8C2/avk66JB3ttLkkm3pYY//NWlDFkOlUtYRHaizOfpd7RgeWOY+hUWFQOi11sITl3S7NfjtteLKTFmFazXrSBT89+/Fe3wfBZasmAThGBsv0XbRrtUjN/8kT6Kub0r6WUj+n0Imu4JkdmNhcE9HdnL6YmMEQsu8Ro4OkCxx8in0uEtcudbIg17gmGEYd6AU7lBzx0iPbksOcPFwC1ck4apl0T1ka9E4TD/o+3dYhpVZOJAHUwFiNpfgkRvRZCnCW+LWxu+cO5Z3kRZi//t7uY/v/OogMxSMMf6vxBHy83fVibspthSMLLqPDxW+ovhZ9n1NB3hpSMN+YLj9bG6DkfGUKgbuDcpVcDIxf5prH8sU+AvEG1SwQpBGNdWdKOA97RjNV3eMaNFM3OucrpE3V4w9hmuV4dqIjgPIWqK/WZSN19XHLsimNQR05Oo+yPIJxJrWz9CpVBmUA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
