travis:
  secure:
    BINSTAR_TOKEN: mxWXhMLqBBk5IsCket+QZVc5zd31g8efRYxVONMEHE+Zbn0AxMTx9VVfPwL6ckMnVJXckrf0vG6Zl09aFzajJgp4ZWvJV/jBGJpXPKDN1GSkXlWFQ7kwJQ1JXzCvZW/bLKFIZFV2Xhm0dBpWXR3i0k3bEj1GtDGqDOZWtazrfrS954u1q0n913F9dcP8undnyJebXJerQPjZfy81xnt6e1WqRsoJ35sTk2AxdHkQElMKDhJhUZvpptnMRV8sadyuhfbHjfKv5YtCX0KJ14c4+MVPeOJphm28cGdg8orryk/entYT6ikH/cleDEFIhHEJkF5HFaWOyeBAckd+uw5O4wPflQxu8424Jo/Ab2+B4DkwVr5CeDoG3/XMXE7oZ4Pqlz8V2Cug2i+xNWkS0g9tY0jbOtVIM4wQCJow1LGG2VjwOvrqM+sdjIFAm9z0ivro3f+6tsyE2kgrUIS36egKrQZ3SwYrYBGsPLXZtZMYmROgMVvLWEUBxW2gppjb/vlqmuSYHsja5Wz3DbleboX0erbMV3DZN5zBJV+zZHfYaR0FFlmcb9w7BR1j90p9Y1jUUa6fED+/7ZlXKq6UFrjtfWmUZWzkR09YzetiOzVFmA+mU/S1m9pC5uI6BRc4mF6s/0ghFEZqDNQftu/x+4o9mjBn/n9ksEyA66NRh6+YnGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
