appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: R1G6+t5GIcsvDTrqXYG7E9BnPbTiTtirl8St3BCU+6lqiuO30DsASJ39NV7clXrX/7sddMm7PS6BM+eIGqzBHHwBL7ZMSekzSmWlHQ3UiplYAhErdf/ANoCLUxCz5Eki5fDmI9YlHK9e85mJBTHiiI0QN/HaWE844b23Z+2pUBlimKdxfvFOHj0SXt/q70Yfxr3ooiIFMa03LuqGcqcsGmHRju8Epb8C2/avk66JB3ttLkkm3pYY//NWlDFkOlUtYRHaizOfpd7RgeWOY+hUWFQOi11sITl3S7NfjtteLKTFmFazXrSBT89+/Fe3wfBZasmAThGBsv0XbRrtUjN/8kT6Kub0r6WUj+n0Imu4JkdmNhcE9HdnL6YmMEQsu8Ro4OkCxx8in0uEtcudbIg17gmGEYd6AU7lBzx0iPbksOcPFwC1ck4apl0T1ka9E4TD/o+3dYhpVZOJAHUwFiNpfgkRvRZCnCW+LWxu+cO5Z3kRZi//t7uY/v/OogMxSMMf6vxBHy83fVibspthSMLLqPDxW+ovhZ9n1NB3hpSMN+YLj9bG6DkfGUKgbuDcpVcDIxf5prH8sU+AvEG1SwQpBGNdWdKOA97RjNV3eMaNFM3OucrpE3V4w9hmuV4dqIjgPIWqK/WZSN19XHLsimNQR05Oo+yPIJxJrWz9CpVBmUA=
